### ISSUE TITLE
[FEATURE]: External Configuration File Support

### ISSUE THREAD

**Issue by nixuuu** [nixcodeit/nixcode-ai#7]
# Feature: External Configuration File Support

## Description

Implement external configuration file support for nixcode-ai following the XDG Base Directory specification for Unix-based systems and appropriate directory structures for Windows. Configuration should be stored in TOML format with layered configuration similar to Git's approach, allowing both project-specific and global configurations.

## Requirements

1. **Configuration File Format**
   - Use TOML as the configuration file format
   - Create a standard configuration schema that can be extended

2. **Configuration Location**
   - Follow XDG Base Directory specification for Unix-based systems:
     - `$XDG_CONFIG_HOME/nixcode/config.toml` (defaults to `~/.config/nixcode/config.toml`)
   - For Windows:
     - `%APPDATA%\nixcode\config.toml`
   - Support project-specific configuration in `.nixcode/config.toml` within project directories

3. **Configuration Hierarchy**
   - Implement cascading configuration that merges settings from multiple sources
   - Order of precedence (highest to lowest priority):
     1. Command-line arguments
     2. Project-specific configuration (`.nixcode/config.toml` in the current directory)
     3. Parent directory configurations (up to file system root)
     4. User-level configuration (XDG or Windows equivalent)
     5. System-wide configuration
     6. Default built-in values

4. **Configuration Options**
   - LLM provider settings (API keys, default models, etc.)
   - UI customization (colors, layout)
   - Default behavior settings
   - Keybindings customization
   - Tool configuration and defaults

## Technical Approach

1. **Create a Configuration Module**
   - Implement in `libs/nixcode/src/config/`
   - Define a `Config` struct that represents all possible configuration options
   - Implement serialization/deserialization using `serde` and `toml`

2. **Configuration Loading System**
   - Create a loader that resolves configuration file paths based on platform
   - Implement configuration merging logic to combine multiple config files
   - Cache configuration to avoid repeated file reading

3. **File System Handling**
   - Detect and create necessary directories if they don't exist
   - Handle file permissions properly
   - Implement file watching for hot-reloading of configuration (future enhancement)

4. **Integration with Existing Code**
   - Create an accessor API for configuration values
   - Replace hardcoded values with configuration-based values throughout the codebase
   - Ensure backward compatibility

## Implementation Plan

1. Create the basic configuration structure and schema
2. Implement platform-specific path resolution
3. Build the configuration loading and merging system
4. Integrate with the application initialization flow
5. Update existing code to use configuration values
6. Add configuration validation
7. Create default configuration files
8. Document configuration options

## Dependencies

- Add the following Rust crates:
  - `toml` for TOML parsing
  - `directories` for XDG/Windows directory resolution
  - `serde` for serialization/deserialization
  - `config` (optional) for advanced configuration merging

## Examples

Example configuration file structure:
```toml
[llm]
default_provider = "anthropic"
default_model = "claude-3-haiku"

[anthropic]
api_key = "${ANTHROPIC_API_KEY}" # Support for environment variable expansion

[openai]
api_key = "${OPENAI_API_KEY}"
default_model = "gpt-4o-mini"

[ui]
theme = "dark"
message_display_mode = "compact"

[keybindings]
normal_mode = { quit = "q", send = "<Enter>" }
insert_mode = { escape = "<Esc>" }

[tools]
enabled = ["glob", "fs", "prompt"]
```

## Related Tickets
- None

## Additional Notes
- Configuration should be reloadable at runtime (if possible)
- Consider implementing a command to edit configuration files
- Add validation for configuration values
- Include comprehensive documentation on available configuration options
